#!/bin/bash
GROUP=monte_carlo
export PATH=/home/darnoc/CASMcode:$PATH
cd /home/darnoc/CASMcode
mkdir -p /home/darnoc/CASMcode/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/home/darnoc/CASMcode/casm_unit_$GROUP ${TEST_FLAGS}
